language: node_js

node_js:
   "12.14.1"

cache:
  directories:
    - node_modules
  yarn: true

install:
  - yarn install

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  email: meghnath.babin@gmail.com
  name: Meghnath Das
  target-branch: gh-pages
  on:
    branch: master