os: linux

language: node_js

node_js:
   "10.14.2"

cache:
  directories:
    - node_modules
  yarn: true

install:
  - yarn install

script:
  - yarn build

deploy:
  provider: pages
  cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  email: meghnath.babin@gmail.com
  name: Meghnath Das
  target_branch: gh-pages
  on:
    branch: master