dist: trusty

sudo: false

os: linux

language: node_js

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

node_js:
   "10.14.2"

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm build
  - mv dist/404.html

deploy:
  provider: pages
  cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  email: meghnath.babin@gmail.com
  name: Meghnath Das
  target_branch: gh-pages
  on:
    branch: master