language: node_js
node_js:
	- 12.14.1
catche: npm

install:
	- npm install

script:
    - npm build --prod

deploy:
	provider: pages
	skip-cleanup: true
	github-token: $GITHUB_TOKEN
	local_dir: dist
	on:
		branch: master
