language: node_js

node_js:
   "10.14.2"

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run-script build

deploy:
  provider: pages
  cleanup: false
  github_token: $GITHUB_TOKEN
  local_dir: dist
  email: meghnath.babin@gmail.com
  name: Meghnath Das
  target_branch: gh-pages
  on:
    branch: master