language: node_js

node_js:
   "12.14.1"

cache:
  directories:
    - node_modules
  npm: true

install:
  - npm install

script:
  - npm build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  email: meghnath.babin@gmail.com
  name: Meghnath Das
  target-branch: gh-pages
  on:
    branch: master